import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import ContextualMenu from '../components/contextualMenu'
import Clock from '../components/clock'
import CustomCursor from '../components/cursor'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Robin Pautigny</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CustomCursor/>
        <ContextualMenu/>
        <Clock/>

        <h1 className={styles.title}>TEST</h1>

        {/* <Link href="/projects">
          <p>projets</p>
        </Link> */}
          

        {/* <h1 className={styles.title}>PORTFOLIO</h1> */}
      </main>
    </>
  )
}
