import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import ContextualMenu from '../components/contextualMenu'
// import Clock from '../components/clock'
import CustomCursor from '../components/cursor'
import Link from 'next/link'
import ProjectsListIndex from '@/components/projectListIndex'
import { useState, useEffect } from 'react'
import ProjectDB from '../utils/articles.json';
import Loader from '../components/loader'


export default function Home() {
  // Assuming you have your projects data here
  const [projects, setProjects] = useState([]);
  const [progress, setProgress] = useState(0);
  const background = ProjectDB.background

  useEffect(() => {
    async function fetchData() {
      setProjects(ProjectDB);
    }
    fetchData();
  }, []);

  useEffect(() => {
    const interval = setInterval(() => {
      setProgress((prevProgress) => {
        if (prevProgress === 100) {
          clearInterval(interval);
          return prevProgress;
        } else {
          return prevProgress + 1;
        }
      });
    }, 10);
  
    return () => {
      clearInterval(interval);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Robin Pautigny</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CustomCursor/>
        <ContextualMenu/>
        {/* <Clock/> */}
        <Loader/>
        <h1 className={styles.title}>FOLIO 20/23</h1>
      </main>
      <div className={styles.progressBar}>
      <div className={styles.progressBarFill} style={{ width: `${progress}%` }}></div>
      </div>
      <div className={styles.progressText}>{progress}%</div>
        <ProjectsListIndex projects={projects} />
    </>
  )
}
